/**用户表**/
CREATE TABLE USER_INFO(

	ID VARCHAR(32)  PRIMARY KEY COMMENT '主键',
	USERNAME VARCHAR(30) NOT NULL COMMENT '用户名',
	PASSWORD VARCHAR(30) NOT NULL COMMENT '密码',
	NAME VARCHAR(30) NOT NULL COMMENT '姓名',
	EMAIL VARCHAR(30) NOT NULL COMMENT 'EMAIL',
	STATE VARCHAR(2) DEFAULT '0' COMMENT '状态：0为正常、1为冻结、2为停用',
	SEX CHAR(2) NOT NULL COMMENT '性别 F为女性、M为男性',
	BIRTHDAY DATE COMMENT '生日',
	GREDUATE_FROM VARCHAR(100) COMMENT '毕业院校',
	GREDUATE_LEVEL VARCHAR(10) COMMENT '学历层次',
	IDCARD_NO VARCHAR(18) COMMENT '身份证号码',
	CELLPHONE_NO VARCHAR(24) COMMENT '手机',
	WECHAT VARCHAR(100) COMMENT '微信号',
	ADDRESS VARCHAR(300) COMMENT '地址',
	POST_CODE VARCHAR(20) COMMENT '邮编',


	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT
);
/**供应商主体表**/
CREATE TABLE SUPPLIER_SUBJECT(

	ID VARCHAR(32) PRIMARY KEY,

	SUPPLIER_NAME VARCHAR(200) NOT NULL COMMENT '供应商名称',
	SUPPLIER_TYPE VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '0为公司客户、1为个人客户',
	SUPPLIER_EMAIL VARCHAR(70) COMMENT '邮件',
	SUPPLIER_LOCATION VARCHAR(50) COMMENT '供货商所属地区',
	SUPPLIER_PHONE VARCHAR(50) COMMENT '供货商电话',
	SUPPLIER_ADDRESS VARCHAR(500) COMMENT '供货商地址',
	SUPPLIER_STATE VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '供货商状态，0为合作、1为不再合作',
	SUPPLIER_REMARK VARCHAR(500) COMMENT '备注',


	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT
);
/**供应商供货联系人表-所属供应商主体**/
CREATE TABLE SUPPLIER_INDIVIDUAL(

	ID VARCHAR(32) PRIMARY KEY COMMENT '主键',
	SUPPLIER_SUBJECT_ID VARCHAR(32) NOT NULL COMMENT '关联供货商主键',
	FOREIGN KEY(SUPPLIER_SUBJECT_ID) REFERENCES SUPPLIER_SUBJECT(ID),

	NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	POSITION VARCHAR(20) COMMENT '职位',
	STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CELLPHONE VARCHAR(30) COMMENT '电话',
	EMAIL VARCHAR(100) COMMENT 'EMAIL',
	REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**客户主体**/
CREATE TABLE CUSTOMER_INFO(

	ID VARCHAR(32) PRIMARY KEY COMMENT '主键',

	CUSTOMER_NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	CUSTOMER_TYPE VARCHAR(20) NOT NULL COMMENT '0是企业客户、1是个人客户',
	CUSTOMER_STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CUSTOMER_CELLPHONE VARCHAR(30) COMMENT '电话',
	CUSTOMER_EMAIL VARCHAR(100) COMMENT 'EMAIL',
	CUSTOMER_ADDRESS VARCHAR(500) COMMENT '客户地址',
	CUSTOMER_REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**客户联系人**/
CREATE TABLE CUSTOMER_LINKS(

	ID VARCHAR(32) PRIMARY KEY COMMENT '主键',

	CUSTOMER_INFO_ID VARCHAR(32) NOT NULL COMMENT '关联客户表',
	FOREIGN KEY(CUSTOMER_INFO_ID) REFERENCES CUSTOMER_INFO(ID),

	NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CELLPHONE VARCHAR(30) NOT NULL COMMENT '电话',
	EMAIL VARCHAR(100) COMMENT 'EMAIL',
	ADDRESS VARCHAR(500) COMMENT '客户地址',
	REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**货品库存表**/
CREATE TABLE STOCK_LIST(

	ID VARCHAR(32) PRIMARY KEY COMMENT '主键',
	STOCK_PRODUCT_NAME VARCHAR(500) NOT NULL COMMENT '商品名称',
	STOCK_PRODUCT_QNO VARCHAR(100) NOT NULL COMMENT '商品条形码',
	STOCK_PRODUCT_LOCATION VARCHAR(50) NOT NULL COMMENT '产地',
	STOCK_PRODUCT_NUM DECIMAL(12,2) NOT NULL COMMENT '进货数量',
	STOCK_PRODUCT_POSITION VARCHAR(10) NOT NULL COMMENT '单位',
	STOCK_PRODUCT_PLUS_NUM DECIMAL(12,2) DEFAULT 0 COMMENT '散货量',
	STOCK_PRODUCT_PLUS_POSITION VARCHAR(10) COMMENT '散货单位',
	STOCK_PRODUCT_FORMAT_NUM DECIMAL(4,2) NOT NULL COMMENT '每件含单件个数',
	STOCK_PRODUCT_GUARANTEE_TIME VARCHAR(20) COMMENT '保质期',
	STOCK_PRODUCT_SINGLE_NETWEIGHT DECIMAL(12,2) COMMENT '单件净含量',
	STOCK_PRODUCT_SINGLE_CAPACITY DECIMAL(12,2) COMMENT '单件体积',
	STOCK_PRODUCT_BATCH VARCHAR(30) COMMENT '批次号，可能同种商品不同批次',
	STOCK_PRODUCT_STATE VARCHAR(20) NOT NULL COMMENT '库存状态：0在途可预售、1在售、2已售罄、3退货在途、4已退货',
	STOCK_PRODUCT_STORAGE VARCHAR(30) COMMENT '库存地',
	STOCK_PRODUCT_WASTAGE DECIMAL(12,4) COMMENT '损耗个数',
	STOCK_PRODUCT_STORAGE_FEE DECIMAL(12,4) COMMENT '仓储费',
	STOCK_PRODUCT_SUPPLIER_SUBJECT_ID VARCHAR(32) NOT NULL COMMENT '关联供应商',
	FOREIGN KEY(STOCK_PRODUCT_SUPPLIER_SUBJECT_ID) REFERENCES SUPPLIER_SUBJECT(ID),


	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**货品库存费用表**/
CREATE TABLE STOCK_LIST_FEE(

	ID VARCHAR(32) PRIMARY KEY COMMENT '主键',

	FEE_TYPE VARCHAR(100) NOT NULL COMMENT '费用种类',
	FEE_NUM DECIMAL(12,2) DEFAULT 0 COMMENT '价格',

	STOCK_LIST_ID VARCHAR(32) NOT NULL COMMENT '关联库存',
	FOREIGN KEY(STOCK_LIST_ID) REFERENCES STOCK_LIST(ID),

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);