/**用户表**/
CREATE TABLE USER_INFO(

	ID VARCHAR(30) PRIMARY KEY COMMENT '主键',
	USERNAME VARCHAR(30) NOT NULL COMMENT '用户名',
	PASSWORD VARCHAR(30) NOT NULL COMMENT '密码',
	NAME VARCHAR(30) NOT NULL COMMENT '姓名',
	STATE VARCHAR(2) DEFAULT '0' COMMENT '状态：0为正常、1为冻结、2为停用',
	SEX CHAR(2) NOT NULL COMMENT '性别 F为女性、M为男性',
	BIRTHDAY DATE COMMENT '生日',
	GREDUATE_FROM VARCHAR(100) COMMENT '毕业院校',
	GREDUATE_LEVEL VARCHAR(10) COMMENT '学历层次',
	IDCARD_NO VARCHAR(18) COMMENT '身份证号码',
	CELLPHONE_NO VARCHAR(24) COMMENT '手机',
	WECHAT VARCHAR(100) COMMENT '微信号',
	ADDRESS VARCHAR(300) COMMENT '地址',
	POST_CODE VARCHAR(20) COMMENT '邮编',


	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT
);
/**供应商主体表**/
CREATE TABLE SUPPLIER_SUBJECT(

	ID VARCHAR(30) PRIMARY KEY,

	SUPPLIER_NAME VARCHAR(200) NOT NULL COMMENT '供应商名称',
	SUPPLIER_TYPE VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '0为公司客户、1为个人客户',
	SUPPLIER_EMAIL VARCHAR(70) COMMENT '邮件',
	SUPPLIER_LOCATION VARCHAR(50) COMMENT '供货商所属地区',
	SUPPLIER_PHONE VARCHAR(50) COMMENT '供货商电话',
	SUPPLIER_ADDRESS VARCHAR(500) COMMENT '供货商地址',
	SUPPLIER_STATE VARCHAR(20) NOT NULL DEFAULT '0' COMMENT '供货商状态，0为合作、1为不再合作',
	SUPPLIER_REMARK VARCHAR(500) COMMENT '备注',


	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT
);
/**供应商供货联系人表-所属供应商主体**/
CREATE TABLE SUPPLIER_INDIVIDUAL(

	ID VARCHAR(30) PRIMARY KEY COMMENT '主键',
	SUPPLIER_SUBJECT_ID VARCHAR(30) NOT NULL COMMENT '关联供货商主键',
	FOREIGN KEY(SUPPLIER_SUBJECT_ID) REFERENCES SUPPLIER_SUBJECT(ID),

	NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	POSITION VARCHAR(20) COMMENT '职位',
	STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CELLPHONE VARCHAR(30) COMMENT '电话',
	EMAIL VARCHAR(100) COMMENT 'EMAIL',
	REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**客户主体**/
CREATE TABLE CUSTOMER_INFO(

	ID VARCHAR(30) PRIMARY KEY COMMENT '主键',

	CUSTOMER_NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	CUSTOMER_TYPE VARCHAR(20) NOT NULL COMMENT '0是企业客户、1是个人客户',
	CUSTOMER_STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CUSTOMER_CELLPHONE VARCHAR(30) COMMENT '电话',
	CUSTOMER_EMAIL VARCHAR(100) COMMENT 'EMAIL',
	CUSTOMER_ADDRESS VARCHAR(500) COMMENT '客户地址',
	CUSTOMER_REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);

/**客户联系人**/
CREATE TABLE CUSTOMER_LINKS(

	ID VARCHAR(30) PRIMARY KEY COMMENT '主键',

	CUSTOMER_INFO_ID VARCHAR(30) NOT NULL COMMENT '关联客户表',
	FOREIGN KEY(CUSTOMER_INFO_ID) REFERENCES CUSTOMER_INFO(ID),

	NAME VARCHAR(30) NOT NULL COMMENT '联系人姓名',
	STATE VARCHAR(20) COMMENT '联系人状态、0为正常、1为不再合作',
	CELLPHONE VARCHAR(30) NOT NULL COMMENT '电话',
	EMAIL VARCHAR(100) COMMENT 'EMAIL',
	ADDRESS VARCHAR(500) COMMENT '客户地址',
	REMARK VARCHAR(500) COMMENT '备注',

	CREATED_BY VARCHAR(30),
	CREATED_DATE TIMESTAMP,
	UPDATE_BY  VARCHAR(30),
	UPDATE_DATE TIMESTAMP,
	VERSION BIGINT

);